### PR TITLE
Fix for plone.org issues 73 and 110

### LINKED ISSUE #73: Center-align columns in Icons and Text block
The "Icons and Text" block columns are left justified.  On mobile especially, center is a better visual.  Here is some css to center image, title, and text within the columns.

.block-icons-text .columns-wrapper .column-block {text-align:center;}
.block-icons-text .columns-wrapper .column-block.divider_before_title .column-head {justify-content: center;}

### LINKED ISSUE #87: Search pane on Bugs page obscured by "There's a bug in my Plone" box
At https://plone.org/community/bugs, clicking on the magnifying glass icon shows the search pane, but it is beneath the "There's a bug in my Plone" box.

I'm using Firefox 109.0 on a Linux desktop, the window is 1074px wide; it appears to be a breakpoint-specific issue as full screen is fine.

### LINKED ISSUE #110: Quick to solve styling issues: header dropdown, centered h2, collapsing paragraph margins below lists.
There are some visual styling issues that are really annoying me and that I'd like to fix or assist other frontenders to fix. They don't seem difficult, but do impact the visuals, so I want to gather some feedback first:

###  main menu drop down

The drop down menu on deskto lets you travel all diagonally over the screen to select a sub menu item. Why aren't these expanded right below the menu item ietself?

Image

###  H2's are centered on the screen, all other head lines are not

What I see now in the content that h1 is the headline and editors use h3's for all sub headlines, because the centered h2 stands out as 'odd' most of the time. Can't we keep the headlines as they are left aligned and allow the centering to work instead if it's necessary visually? The problem is that a lot of old content now has centered subtitles on h2. 

Image

### Links are not accessible and difficult to spot

For me the links in this screenshot are almost invisible. Can't we please underline them? Or have an expert figure out the colors for all possible combinations of color blindness? (read: that's almost impossible, just have underlines in the main content text. ) 

Image

### PR DESCRIPTION
**Pull request by miropaananen**
Fixes #73
Fixes #110

### CODE REVIEW

**Comment by miropaananen** [comment]
I deleted issue 87. I taught I had fixed it but I tested my changes again and the issue still persisted. Sorry for the inconvenience. I think had investigated it but ran out of time during the sprint.

**Comment by Fosten** [comment]
Removing h2 {text-align: center;} in site.overrides should also fix Issue #109 but may cause unwanted formatting issues in other places.  I agree it should be removed, but content will need to be reviewed afterwards to see if we need re-add h2 {text-align: center;} in places where it is desired.

**Review by fredvd — APPROVED** [review]
LGTM, thanks Miro

**Comment by stevepiercy** [comment]
See also https://github.com/plone/plone.org/issues/155. I'm not sure whether this pull request fixes it.

**Pull request merged**
