### PR TITLE
Darker link color for accessibility

### LINKED ISSUE #20: Fix color contrast in body links to reach AA-level accessibility
Current contrast in blue links is too low. Change the color to #005B85 or darker to achieve #AAA level accessibility. 
Example https://beta.plone.org/why-plone/features

### PR DESCRIPTION
**Pull request by pnicolli**
Fixes #20 

But I think it might need a little more effort, this is the result with the color provided in the related issue, but I think it's a little too similar to the text color. What do you think?

Schermata 2022-12-09 alle 22 32 37

### CODE REVIEW

**Comment by sneridagh** [comment]
@pnicolli @rioksane I agree, the difference is difficult to tell

**Comment by rioksane** [comment]
@pnicolli @sneridagh how about just adding underline to content links (P, span, LI)? Then it can be separated from regular text. Underlines are not as pretty as without them but in the content section they would be OK, I think.  

Headings or special blocks would go just with the color change, no underlines there.

**Comment by rioksane** [comment]
Like this
Screenshot 2022-12-11 at 11 48 14

**Review by rioksane — APPROVED** [review]
It's better with the new color, since it AA accessible.

**Pull request merged**
