### PR TITLE
Cookie banner improvement

### LINKED ISSUE #13: Cookie banner improvements and fixes
The cookie banner in the https://beta.plone.org site could use some work. 

Screenshot 2022-11-11 at 19 12 12

- Bug: the X close button the right corner always mimimizes user choises to only functional cookies
- Improvement: It is not generally goo to emphasize Accept all -button. Better to emphasize "only necessary" or "save my preferences"
- Feature: need to add/change Google Analytics to Matomo - since we use that to analytics. However, if/when we use YouTube embeds (for Plone 6 screencasts or other), we need to allow Google advertisement cookies. 
- Improvement: Make the cookie button less obtrusive on the mobile view? Put it to footer maybe? This is just nice to have. 
- Bug: Fix cookie banner contrast issues (image below, tested with Wave toolbar):

### PR DESCRIPTION
**Pull request by pnicolli**
Fixes #13 

Feel free to decide whether to move the discussion here from the issue or to keep it there, I am happy with both solutions.

This is the banner after the first commit of this PR.

image

### CODE REVIEW

**Review by rioksane — APPROVED** [review]
I think the most obvious needed thing was to mention Matomo and it is there. We probably need to come back to further improve this, but that can be done later when we better decide what we need.

**Comment by fredvd** [comment]
Please don't merge this one yet, I'm working on some other improvements we talked about: moving the bit too prominent fixed cookie settings icon on the right border into the footer. 

But we don't have enough room in the current layout so I've condensed the socials into 2 subcolunns in the last grid.

footer-social-cookie-settings

Fixing some last issues with the mobile size & indent

footer-social-mobile

**Comment by fredvd** [comment]
Done. Updated the privacy statement texts and change the title to 'Privacy Policy' in the footer with an internal link to /privacy-poliy becaue of #72 

One minor styling issue left, the 2 column socials indent on mobile widths.... but not on desktop.  something in the footer.less, but can be solved later, no blocker.

privacy settings modal texts

**Review by rioksane — APPROVED** [review]
Hmm. I'm not sure about the two extra columns for social media but if you it works  responsively enough then I guess it's fine.

**Pull request merged**
