### PR TITLE
Foundation Member workflow and default view

### LINKED ISSUE #124: Foundation Member workflow improvement
# Summary

- [x] Review existing Permission
- [ ] Update Rolemap
- [ ] Update Workflow
- [ ] Add upgrade step to update permission on existing objects
- [ ] Add tests

### PR DESCRIPTION
**Pull request by ericof**
Fixes #124

### CODE REVIEW

**Review by fredvd — APPROVED** [review]
lgtm. thanks!

**Comment by Fosten** [comment]
You may wish to consider #119 in the new Member view.

**Comment by fredvd** [comment]
So @ericof did create a custom view for the member view , but maybe it is still listing too much. 

https://github.com/plone/plone.org/pull/129#issuecomment-1572251039

**Comment by ericof** [comment]
@fredvd, @Fosten: We now show the information only to users with the correct permissions. The problem to be solved is the fact we have way too many people with Editor rights on the site

**Pull request merged**
